[package]
name = "ynhs-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
wry = "0.35"
tao = { version = "0.24", features = ["rwh_05"] }
webbrowser = "0.8"
image = { version = "0.24", default-features = false, features = ["png"] }
tray-icon = "0.14"

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
